# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
version: 0.0
os: linux
files:
  - source: /api
    destination: /var/gameengineservice/v2/api/
hooks:
  ApplicationStart:
    - location: api/run_api.sh
      runas: ec2-user
  ApplicationStop:
    - location: deployment/clean_up.sh
      runas: root
