# This is an appspec.yml template file for use with an EC2/On-Premises deployment in CodeDeploy.
version: 0.0
os: linux
files:
  - source: /api
    destination: /var/gameengineservice/api/v3/
hooks:
  ApplicationStart:
    - location: api/run_api.sh
      runas: ec2-user
