# This is the CI workflow to deploy the Game Engine Service to staging on EC2 with CodeDeploy

name: Deploy staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]
    paths:
    - '.github/workflows'
    - 'api/**'
    - '!api/README.md'
    - 'deployment/**'
    - '!deployment/README.md'
    - 'appspec.yml'

jobs:
  validate_staging:
    name: Validate the staging deployment version and port
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Validate
      run: ./deployment/validate_staging.sh

  deploy_staging:
    needs: validate_staging
    name: Deploy with CodeDeploy to staging on EC2
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
        role-duration-seconds: 1200
        role-session-name: CodeDeploySession

    - name: Create a staging deployment with CodeDeploy
      run: |
        aws deploy create-deployment    --application-name GameEngineService    --deployment-config-name CodeDeployDefault.OneAtATime    --deployment-group-name GameEngineService-Staging    --description "Automated v2 staging deployment with GitHub Action+CodeDeploy to EC2"    --github-location repository=Blef-team/blef_game_engine,commitId=${{ github.sha }}

  test_staging:
    needs: deploy_staging
    name: Test the staging deployment
    runs-on: ubuntu-latest

    steps:
    - name: Test
      run: BASE_URL="http://18.132.35.89:8011/v2" ./api/test/run.sh
